#
# Makefile for HDMI sii9334 chip drivers.

#obj-$(CONFIG_MHL_Sii8334)	+= SiI9244_I2C.o
#obj-$(CONFIG_MHL_Sii8334)	+= sii9244_driver.o
#obj-$(CONFIG_MHL_Sii8334)	+= sii_mhltx.o
#obj-$(CONFIG_MHL_Sii8334)	+= MHL_SiI9244.o

#ccflags-$(CONFIG_I2C_DEBUG_BUS) := -DDEBUG

#obj-$(CONFIG_MHL_Sii8334)	+= si_cra_cfg.o


obj-$(CONFIG_MHL_Sii8334)	+= si_cra.o

obj-$(CONFIG_MHL_Sii8334)	+= si_mhl_tx_rcp_table.o
obj-$(CONFIG_MHL_Sii8334)	+= si_drv_mhl_tx.o
obj-$(CONFIG_MHL_Sii8334)	+= si_mhl_tx.o
obj-$(CONFIG_MHL_Sii8334)	+= MHL_SiI8334.o
